<?php
use Livewire\Component;
new class extends Component {
 public \App\Models\Quiz $quiz; public string $name = ''; public string $email = ''; public array $answers = []; public int $step = 0;
 public function mount(\App\Models\Quiz $quiz): void { abort_unless($quiz->is_published, 404); $this->quiz = $quiz->load('questions.options'); }
 public function next(): void { $this->validate(['answers.'.$this->quiz->questions[$this->step - 1]->id => 'required']); $this->step++; }
 public function previous(): void { $this->step--; }
 public function submit(): void { $rules = ['name' => 'required|string|max:100', 'email' => 'nullable|email']; foreach ($this->quiz->questions as $question) { $rules['answers.'.$question->id] = 'required|exists:options,id'; } $this->validate($rules); $score = 0; $maxScore = $this->quiz->questions->sum('points'); $submission = \App\Models\Submission::create(['quiz_id' => $this->quiz->id, 'participant_name' => $this->name, 'participant_email' => $this->email ?: null, 'max_score' => $maxScore, 'completed_at' => now()]); foreach ($this->quiz->questions as $question) { $option = $question->options->firstWhere('id', (int) $this->answers[$question->id]); $earned = $this->quiz->type === 'assessment' ? $option->value : ($option->is_correct ? $question->points : 0); $score += $earned; $submission->answers()->create(['question_id' => $question->id, 'option_id' => $option->id, 'value' => $option->value]); } $submission->update(['score' => $score, 'percentage' => $maxScore ? (int) round(($score / $maxScore) * 100) : 0]); $this->redirectRoute('results.show', $submission, navigate: true); }
}; ?>
<div class="assessment">@if ($step === 0)<section class="start-panel"><p class="eyebrow">{{ $quiz->type === 'assessment' ? 'SELF ASSESSMENT' : 'QUIZ' }}</p><h1>{{ $quiz->title }}</h1><p>{{ $quiz->description }}</p><div class="form-grid"><label>Nama<input wire:model="name" placeholder="Nama panggilan"></label><label>Email <small>(opsional)</small><input wire:model="email" type="email" placeholder="nama@email.com"></label></div><button class="button" wire:click="$set('step', 1)">Lanjutkan</button></section>@else @php($question = $quiz->questions[$step - 1])<section class="question-panel"><div class="progress"><span style="width: {{ (($step - 1) / $quiz->questions->count()) * 100 }}%"></span></div><p class="question-count">PERTANYAAN {{ $step }} / {{ $quiz->questions->count() }}</p><h1>{{ $question->question }}</h1><div class="options">@foreach ($question->options as $option)<label class="option"><input type="radio" wire:model="answers.{{ $question->id }}" value="{{ $option->id }}"><span>{{ $option->label }}</span></label>@endforeach</div>@error('answers.'.$question->id)<p class="error">Pilih satu jawaban untuk melanjutkan.</p>@enderror<div class="actions">@if($step > 1)<button class="button secondary" wire:click="previous">Kembali</button>@endif @if($step < $quiz->questions->count())<button class="button" wire:click="next">Berikutnya</button>@else<button class="button" wire:click="submit">Lihat hasil</button>@endif</div></section>@endif</div>
